### ISSUE TITLE
Add email verification

### ISSUE THREAD

**Issue by amgoodfellow** [RecCenterManagement/CSI4999-Workspace#1]
## Overview
After a user has registered with the service, and _before_ they can log in, we need to validate the email address we have for them. This would mean we have to send an email with some sort of link inside of it. Maybe it includes a URL query param that only lasts for two days? That URL param will have to be long enough so that it's not easily guessable. Maybe we could make it a hash of their username, email, and the current systime.

### Checklist:

- [ ] An email is sent to a user after registration
- [ ] An endpoint exists for user email validation (using either query params or path variables)
- [ ] The endpoint updates the database showing that the user has a valid email
- [ ] If a user has remained unvalidated for more than two days, they are removed from the table 

Requirement Addressed: 1.7

**Comment by EliteMasterEric** [comment]
This may already be implemented; I will work on this task.

**Comment by EliteMasterEric** [comment]
I'd say this issue is complete. The credential issues are in a separate issue, issue #6 .
