### ISSUE TITLE
Entity Design / Creation

### ISSUE THREAD

**Issue by amgoodfellow** [RecCenterManagement/CSI4999-Workspace#3]
## Overview
JHipster JDL creates some super nice ERDs based on an almost SQL-like dialect. It would be pretty cool if we could get all of our user authentication / role authorization done, _and_ have some pretty ERDs for the next sprint.
This is basically a database planning tool. Be sure to confirm your design with the group before implementing.

**Comment by ghost** [comment]
I have created a prototypical set of JDL declarations for our initial entity model here at https://github.com/RecCenterManagement/notes/blob/master/entity-model.jdl

#4 is being worked on as discussed at our meeting on 9/17
