### ISSUE TITLE
User Entity Creation

### ISSUE THREAD

**Issue by amgoodfellow** [RecCenterManagement/CSI4999-Workspace#4]
## Overview
This is in its own card because it has a higher priority than issue #3. 
In order for other members to finish their sprints, the schema for users has to be decided and implemented.

I'm not sure exactly what's all needed but I imagine it would have to look something like:
```sql
create table user {
  id serial primary key, 
  username text not null,
  password_hash text not null,
  email text not null,
  email_validated boolean default false,
  bad_actor boolean default false
}
```
With an additional table enumerating roles, and then maybe (if we wanted to be proper) a joining table where you have user ids matching up with role ids.

Although I realize we're not actually writing real sql here, so I'm not sure the equivalent in like, JPA land.

**Comment by EliteMasterEric** [comment]
For reference, the User entity is laid out here:

https://github.com/RecCenterManagement/CSI4999-Workspace/blob/master/src/main/java/edu/oakland/domain/User.java

EDIT: You can view information about the database in memory here: http://localhost:8080/h2-console

**Comment by EliteMasterEric** [comment]
Instructions on creating new entities and updating existing entities: https://www.jhipster.tech/creating-an-entity/

**Comment by ghost** [comment]
ExtendedUser entity has been created and will be used to hold additional user configurations
